require('plugins')
require('keymappings')
require('settings')
require('colorscheme')
require('options')


-- Plugins
require('nv-icons')
require('nv-cmp')
require('nv-colorizer')
require('nv-lualine')
require('nv-treesitter')
require('nv-autopairs')
require('nv-autotags')
require('nv-git')
require('nv-comment')
require('nv-telescope')
require('nv-fzf')
require('nv-mason')
require('nv-hop')
require('nv-trouble')

-- LSP
require('lsp')
--require('lsp.hs-ls')
require('lsp.lua-ls')
require('lsp.python-ls')
require('lsp.rust-ls')
require('lsp.c_sharp-ls')
require('lsp.ts-ls')
require('lsp.elixir-ls')
